### ISSUE TITLE
Promote wider adoption of GitHub ecosystem

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [moj-analytical-services/dmet-cfe#15]
- [x] Use GitHub project for [centralised roadmap](https://github.com/orgs/moj-analytical-services/projects/89)
- [x] Create monthly extract from centralised roadmap for Richard Prices' office (see https://github.com/moj-analytical-services/data-and-analytics-engineering-activities/pull/16)
- [x] https://github.com/ministryofjustice/data-and-analytics-engineering/pull/11
- [x] Present at Data and Analytics Engineering Community Forum [LINK](https://drive.google.com/file/d/1UlgRz66bBDKzY5ppY7L7Be85ouQkfSme/view)
- [x] Present at DEDS Show and Tell [LINK](https://justiceuk-my.sharepoint.com/:v:/g/personal/vlad_pasca_justice_gov_uk/ESnkMIUCf8tJqL49jRpX_EcBBAeKhGkz5XGifKk_0T35kQ?e=2nHpoP)
